//  Import dart and flutter packages.
import 'package:flutter/material.dart';

// Import project-specific files.
// import 'package:kar_kam/animation_status_notification.dart';
import 'package:kar_kam/app_settings.dart';
import 'package:kar_kam/button.dart';
import 'package:kar_kam/button_specs.dart';

/// [ButtonArray] implements a linear button array on screen.
class ButtonArray extends StatelessWidget {
  const ButtonArray({Key? key}) : super(key: key);

  /// [buttonSpecList] defines the specs for each button on the screen.
  static List<ButtonSpec> buttonSpecList = [
    settingsButton,
    filesButton,
    homeButton,
  ];

  List<Widget> buttonList(List<ButtonSpec> buttonSpecList) {
    //  Initialise widgetList so that it is ready for population.
    List<Widget> widgetList = [];

    //  Loop over items in buttonSpecList and convert each to its
    //  corresponding button.
    buttonSpecList.forEach((element) => widgetList.add(Button(element)));

    return widgetList;
  }

  @override
  Widget build(BuildContext context) {
    //  Use a Container-Align-Column construct to position items in the list
    //  generated by the slidingButtonList method.
    return Container(
      //  Request that this container expands to fit the entire screen.
      //  Required for calculating the button start position off-screen.
      constraints: BoxConstraints.expand(
        width: double.infinity,
        height: double.infinity,
      ),
      //  Position the button array according to Align specs.
      //  Specs provided by AppSettings.
      child: Align(
        alignment: AppSettings.buttonAlignment,
        child: Flex(
          direction: AppSettings.buttonAxis,
          textDirection: (AppSettings.buttonAlignment.x < 0)
              ? TextDirection.ltr
              : TextDirection.rtl,
          crossAxisAlignment: CrossAxisAlignment.center,
          verticalDirection: (AppSettings.buttonAlignment.y < 0)
              ? VerticalDirection.down
              : VerticalDirection.up,
          children: buttonList(buttonSpecList),
        ),
      ),
    );
  }
}
