//  Import flutter packages.
import 'dart:math' as math;
import 'package:flutter/material.dart';

// Import project-specific files.
import 'package:kar_kam/lib/rect_extension.dart';

/// [SettingsPageListTileClipper] calculates the path to clip against when
/// constructing [SettinsgPageListTile].
///
/// The path generated by [SettingsPageListTileClipper] is calculated from
/// an instance of RRect that has been shortened horizontally in order to
/// account for the presence of guestRect.
class SettingsPageListTileClipper extends CustomClipper<Path> {
  const SettingsPageListTileClipper({
    required this.context,
    required this.guestRect,
    Listenable? reclip,
  }) : super(reclip: reclip);

  /// [guestRect] is the Rect which [SettingsPageListTileClipper] creates
  /// a path to avoid.
  final Rect? guestRect;

  //  Required on order to find the current renderBox.
  final BuildContext context;

  @override
  Path getClip(Size size) {
    //  Construct [hostRect] (in this instance the Rect associated with
    //  [SettingsPageListTile] in a coordinate system local to itself).
    Rect hostRect = getHostRect(size);

    //  Only needed for old code below to work. Delete when completed.
    Rect localGuestRect = getLocalGuestRect();

    //  Calculate [deltaX], the amount by which SettingsPageListTile is
    //  clipped by.
    double deltaX = getDeltaX(hostRect);
    print(deltaX);

    // Calculate [relativeOffset] to determine whether to clip left ot right.
    Offset relativeOffset = localGuestRect.center - hostRect.center;

    //  Generate a Path variable representing the boundary of hostRect.
    Path hostPath = Path();
    if (relativeOffset.dx >= 0) {
      //  localGuestRect is to the right of hostRect.
      hostPath
        ..addRRect(RRect.fromRectAndRadius(
            Rect.fromLTRB(hostRect.left, hostRect.top, hostRect.right - deltaX,
                hostRect.bottom),
            Radius.circular(25)));
    } else if (relativeOffset.dx < 0) {
      //  localGuestRect is to the left of hostRect.
      hostPath
        ..addRRect(RRect.fromRectAndRadius(
            Rect.fromLTRB(hostRect.left - deltaX, hostRect.top, hostRect.right,
                hostRect.bottom),
            Radius.circular(25)));
    }
    return hostPath;

    //  Generate a Path variable representing the boundary of guestRect.
    Path guestPath = Path();
    guestPath
      ..addRRect(RRect.fromRectAndRadius(localGuestRect, Radius.circular(15)));

    //  Create the clipPath by subtracting guestPath from hostPath.
    return Path.combine(PathOperation.difference, hostPath, guestPath);
  }

  double getDeltaX(Rect hostRect) {
    //  Convert guestRect, provided as input to [SettingsPageListTileClipper],
    //  from global coordinates to a coordinate system local to current
    //  instance of [SettingsPageListTile].
    Rect localGuestRect = getLocalGuestRect();

    //  [getUpperLocalConstructionRect], [getLowerLocalConstructionRect]
    //  and [centralLocalConstructionRect] provide construction rectangles
    //  used for calculating deltaX.
    Rect upperLocalConstructionRect = getUpperLocalConstructionRect();
    Rect lowerLocalConstructionRect = getLowerLocalConstructionRect();
    Rect centralLocalConstructionRect = getCentralLocalConstructionRect();

    if (hostRect.overlaps(upperLocalConstructionRect)) {
      return 20.0;
    } else if (hostRect.overlaps(lowerLocalConstructionRect)) {
      return 40.0;
    } else if (hostRect.overlaps(centralLocalConstructionRect)) {
      return localGuestRect.width;
    } else {
      return 0.0;
    }
  }

  /// [getHostRect] converts size associated with the current instance
  /// od [SettingsPageListTile] to Rect.
  Rect getHostRect(Size hostSize) => Offset(0.0, 0.0) & hostSize;

  Rect getLocalGuestRect() {
    //  Get [renderBox] associated with [SettingsPageListTileClipper].
    //  (Used to generate guestRect and localGuestRect.)
    RenderBox renderBox = context.findRenderObject() as RenderBox;

    //  Get the global offset associated with the top left corner of
    //  [SettingsPageListTile] relative to the top left screen corner.
    Offset offset = renderBox.globalToLocal(Offset(0.0, 0.0));

    //  Transform guestRect from the global coordinate system relative to the
    //  top left screen corner to a system local to [renderBox], which
    //  represents the current local instance of ListTile.
    return guestRect!.shift(offset);
  }

  /// [getCentralLocalConstructionRect] calculates the central Rect used
  /// for determining the [deltax] by which the current instance of
  /// [SettingsPageListTile] is clipped in the horizontal direction
  /// when interacting with the central part of [ButtonArray].
  ///
  /// Note the output Rect could have zero height.
  Rect getCentralLocalConstructionRect() {
    Rect localGuestRect = getLocalGuestRect();
    return localGuestRect.inflateToHeight(
        math.max(0.0, localGuestRect.height - localGuestRect.shortestSide));
  }

  /// [getLowerLocalConstructionRect] calculates the lower Rect used
  /// for determining the [deltax] by which the current instance of
  /// [SettingsPageListTile] is clipped in the horizontal direction
  /// when interacting with the curved path BELOW [ButtonArray].
  Rect getLowerLocalConstructionRect() {
    Rect localGuestRect = getLocalGuestRect();
    double height = localGuestRect.shortestSide * 1.5;
    double dy = (localGuestRect.height - localGuestRect.shortestSide) / 2.0;
    return localGuestRect.inflateToHeight(height).translate(0.0, dy);
  }

  /// [getUpperLocalConstructionRect] calculates the upper Rect used
  /// for determining the [deltax] by which the current instance of
  /// [SettingsPageListTile] is clipped in the horizontal direction
  /// when interacting with the curved path ABOVE [ButtonArray].
  Rect getUpperLocalConstructionRect() {
    Rect localGuestRect = getLocalGuestRect();
    double height = localGuestRect.shortestSide * 1.5;
    double dy = (localGuestRect.height - localGuestRect.shortestSide) / 2.0;
    return localGuestRect.inflateToHeight(height).translate(0.0, -dy);
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) {
    return true;
  }
}
